### PR TITLE
1.6.3 dependency

### PR DESCRIPTION
**Pull request by 3arthqu4ke**

### CODE REVIEW

**Comment by 3arthqu4ke** [comment]
AHHHHHHHHHHHHHHHHHHH

**Comment by Zane2b2t** [comment]
Sexo

**Review by Zane2b2t — APPROVED** [review]
I approve

**Review by Zane2b2t — APPROVED** [review]

**Comment by Pranav-4043** [comment]
bro this client is taking 2-3 minutes to go to the nether and also many times it kicks me out of the server and also it is very slower than vanilla, also i like this modules of this client please can u fix these issues

**Pull request closed without merging**
